config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: "welcome#index", as: "home"

  get '/goldenrod', to: "goldenrod#index", as: "gold"
  get '/lightcoral', to: "lightcoral#index", as: "coral"
  get '/lightseagreen', to: "lightseagreen#index", as: "seagreen"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goldenrod_controller.rb
class GoldenrodController < ApplicationController
end

app/controllers/lightcoral_controller.rb
class LightcoralController < ApplicationController
end

app/controllers/lightseagreen_controller.rb
class LightseagreenController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goldenrod_helper.rb
module GoldenrodHelper
end

app/helpers/lightcoral_helper.rb
module LightcoralHelper
end

app/helpers/lightseagreen_helper.rb
module LightseagreenHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/goldenrod/index.html.erb
<% content_for :heading do %>
  Goldenrod#index
<% end %>

<ul>
  <li>Is the background Goldenrod?</li>
  <li>Is it still goldenrod when you refresh?</li>
  <li>Does the view count increment when you click the link?</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JavascriptExplorerRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<h1>
  <%= yield :heading %>
</h1>

<div class="row">
  <div class="col-md-3">
    <ul class="list-group col-md-12">
      <li id="home" class="list-group-item">
        <%= link_to_unless_current "Home", {controller: "welcome", action: "index"} %>
        <span class="view_count badge"></span>
      </li>
      <li id="goldenrod" class="list-group-item">
        <%= link_to "Goldenrod", gold_path %>
        <span class="view_count badge"></span>
      </li>
      <li id="lightcoral" class="list-group-item">
        <%= link_to "Lightcoral", coral_path %>
        <span class="view_count badge"></span>
      </li>
      <li id="lightseagreen" class="list-group-item">
        <%= link_to "Lightseagreen", seagreen_path %>
        <span class="view_count badge"></span>
      </li>
    </ul>
  </div>
  <div class="well col-md-8 col-md-offset-1">
    <%= yield %>
  </div>
</div>



</body>
</html>

app/views/lightcoral/index.html.erb
<% content_for :heading do %>
  Lightcoral#index
<% end %>

<ul>
  <li>Is the background lightcoral?</li>
  <li>Is it still lightcoral when you refresh?</li>
  <li>Does the view count increment when you click the link?</li>
</ul>

app/views/lightseagreen/index.html.erb
<% content_for :heading do %>
  Lightseagreen#index
<% end %>

<ul>
  <li>Is the background Seagreen?</li>
  <li>Is it still seagreen when you refresh?</li>
  <li>Does the view count increment when you click the link?</li>
</ul>

app/views/welcome/index.html.erb
<% content_for :heading do %>
  Welcome#index
<% end %>

<p>
  <strong>Challenge 1</strong>: When you click on a color page, your background color should change to match the name of the color in your url path.
  <ul>
    <li>Does it work on refresh?</li>
    <li>Does it work when you click through to the page?</li>
    <li>Is your solution DRY?</li>
  </ul>
</p>
<p>
<strong>Challenge 2</strong>: The counter should increase for every individual page view.
  <ul>
    <li>Do all the numbers reset when you refresh? (good!)</li>
    <li>Do specific numbers increment on each pageview?</li>
    <li>Is your solution DRY?</li>
  </ul>
</p>